# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 61cb82edf079e9120e9ff3cb1592b91e0f51628e56b5ea04177468e4c6c4e48316968fc156a2af14507290f03a88b17e38a7b43ad5f2e5ffab1e998f29a7863b

test:
  secret_key_base: c6058906fd65e483883921af19121281230e11f2fe49667a709fc8c0262c74382101b86eba3b9136b5b5f1205ce5825b9afc527ba396873a6b3b0b0e7f28f039

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
